title: Büro Bichsel
email: mail@beatmazenauer.ch
description: "Büro Bichsel: Projekt für ein mobiles Museum"
baseurl: ""
host: 0.0.0.0
url: "https://www.buero-bichsel.ch"
sass:
    sass_dir: assets/sass
source: .